In [1]:
import numpy as np

In [3]:
a = np.zeros((3,4))

In [4]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
b = np.empty((3,3), dtype='int')

In [6]:
b

array([[        0,         1,         0],
       [      494,       368,         0],
       [      768,         0, 668033792]])

In [2]:
c = np.arange(1,10,2)

In [3]:
c

array([1, 3, 5, 7, 9])

In [5]:
from numpy import pi

In [6]:
d = np.linspace(0,2 * pi, 10)

In [7]:
d

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [8]:
f = np.sin(30)

In [9]:
f

-0.9880316240928618

In [10]:
n = np.array([[1,2,3,4],[2,3,4,5]])

In [17]:
b = np.array([1,2,3,4,5,6,7,8]).reshape((2,4))

In [18]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
r = n*b

In [14]:
r

array([[ 1,  4,  9, 16],
       [10, 18, 28, 40]])

In [19]:
ex = [1,2,3]
np.exp(ex)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [20]:
np.sqrt(ex)

array([1.        , 1.41421356, 1.73205081])

In [15]:
def f(x, y):
    return 4 * x + y

b = np.fromfunction(f, (3, 3), dtype=int)

In [16]:
b

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [50]:
b[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [51]:
b[-1]

array([ 8,  9, 10])

In [52]:
for row in b:
    print(row)

[0 1 2]
[4 5 6]
[ 8  9 10]


In [55]:
for i in b.flat:
    print(i)

0
1
2
4
5
6
8
9
10
